"""fix direct message columns

Revision ID: b2022c15d764
Revises: a74f269f1a71
Create Date: 2026-07-12 06:16:58.301549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2022c15d764'
down_revision: Union[str, Sequence[str], None] = 'a74f269f1a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_messages', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('direct_messages', 'message',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('direct_messages', 'message',
               existing_type=sa.Text(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('direct_messages', 'created_at')
    # ### end Alembic commands ###
