"""create activities table

Revision ID: 9e3ed326105c
Revises: a5497024be07
Create Date: 2026-07-08 17:19:22.668352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3ed326105c'
down_revision: Union[str, Sequence[str], None] = 'a5497024be07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('TASK_CREATED', 'TASK_UPDATED', 'TASK_STATUS_UPDATED', 'TASK_DELETED', 'MEMBER_ADDED', 'MEMBER_REMOVED', 'TEAM_CREATED', 'TEAM_UPDATED', 'TEAM_DELETED', name='activityaction'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_task_id'), 'activities', ['task_id'], unique=False)
    op.create_index(op.f('ix_activities_team_id'), 'activities', ['team_id'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_team_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_task_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
